### ISSUE TITLE
Is there a way to lint doctest compatible code examples.

### ISSUE THREAD

**Issue by proofit404** [johnfraney/flake8-markdown#1]
Hi, thank you for the meaningful package!

I prefer to write my code examples to be compatible with python doctest module.

```python
>>> class broken( object ):
...     def IsThereAReason(notself, **k):
...         pass
```
It would be great if we will be able to lint this code :)

P.S. Is there a chance you will start to use complete markdown parser and run flake8 through API and not subprocesses?

I understand this approach works right now, but in future, it will case support troubles.

Regards, Artem.

**Comment by johnfraney** [comment]
@proofit404 You're welcome! That's an interesting idea. It would be possible to add an additional regex rule to lint a [`pycon`](http://pygments.org/docs/lexers/#pygments.lexers.python.PythonConsoleLexer) block like this:

    ```pycon
    >>> class broken( object ):
    ...     def IsThereAReason(notself, **k):
    ...         pass
    ```

I'd just have to strip the first 4 characters off each line. That sounds like a fun feature to add.

About the subprocess: I was just looking today at [flake8-rst](https://github.com/kataev/flake8-rst), which I did realize existed when I started working on this. I'll see what I can learn from that project.

**Comment by johnfraney** [comment]
@proofit404 I got a working version of this feature. Given [this file](https://gist.github.com/johnfraney/16401235244426200cf639d9fa6fb348), `flake8-markdown` outputs these errors:

```
tests/samples/pycon.md:10:11: F821 undefined name 'characterr'
tests/samples/pycon.md:17:10: E999 SyntaxError: EOL while scanning string literal
tests/samples/pycon.md:25:1: F821 undefined name 'false'
```

I want to clean up the code some more and add more tests before I publish this. You can try this feature in the [`lint-pycon-blocks` branch](https://github.com/johnfraney/flake8-markdown/tree/lint-pycon-blocks).

After this feature release, I'm going to turn this into a proper Flake8 plugin. Thanks again for the suggestions!

**Comment by proofit404** [comment]
Good job! Thanks for the time you have invested in it.

**Comment by johnfraney** [comment]
@proofit404 Thanks, thanks. I should be able to get this published this evening. One quirk that I'll mention in the README is that the code examples should end with a newline. Flake8 complains about the "file" not ending with a newline, and  `doctest` needs it, too. Without the newline, `doctest` thinks that the three backticks are part of the expected output.

**Comment by proofit404** [comment]
:tada: :cake: :tada:
